# Generated by Django 5.1.4 on 2024-12-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='lat',
            field=models.FloatField(default=41.3851),
        ),
        migrations.AddField(
            model_name='escola',
            name='lon',
            field=models.FloatField(default=2.1734),
        ),
    ]
